=head1 NAME

Statistics::Basic::_TwoVectorBase - base class objects like Correlation

=head1 METHODS

=over 4

=item B<insert()>

Insert two new new values into the vectors.  This function must be given
precisely two arguments and probably shouldn't be undefined values in most
cases.

    $correlation_object->insert( 4, 3 );

=item B<ginsert()>

The growing insert inserts new elements, growing the max size of the vector to
accommodate the new elements (if necessary).  This function must be given
precisely two arguments and probably shouldn't be undefined values in most
cases.


    $correlation_object->ginsert( 4, 3 );

=item B<size()>

The current size of the vectors -- regardless of their max size as set by
L</set_size()>.  This function returns a list, i.e.:

    my @s = $cor->size; # two values
    my $s = $cor->size; # the right hand value of the list

=item B<set_size()>

Set the maximum size for the underlying L<Statistics::Basic::Vector> objects.
This function requires two arguments.

=item B<set_vector()>

Set the vector objects used to calculate the correlation.  This function takes
two arguments -- which can either be arrayrefs or L<Statistics::Basic::Vector>
objects.  They must have the same number of elements.

=back

=head1 OVERLOADS

This object is overloaded.  If evaluated as a string, it will attempt to print a
pretty value for the correlation (or C<n/a>, see L</query()> above).

If evaluated as a number, it will try to return the raw result of L</query()>,
possibly turning the resulting undef (if applicable) into a 0 in the process --
note that Perl does this 0-izing, not the overload.

The C<eq> and C<==> operators are also overloaded, trying to do the right thing.
Also see L<$ENV{TOLER}|Statistics::Basic/$ENV{TOLER}> for further information.

=head1 AUTHOR

Paul Miller C<< <jettero@cpan.org> >>

=head1 COPYRIGHT

Copyright 2009 Paul Miller -- Licensed under the LGPL

=head1 SEE ALSO

perl(1), L<Statistics::Basic>

=cut
