=head1 NAME

Statistics::Basic::Covariance - find the covariance between two arrays

=head1 SYNOPSIS

Invoke it this way:

    my $covariance = covariance( [1,2,3], [1,2,3] );

Or this way:

    my $v1  = vector(1,2,3);
    my $v2  = vector(1,2,3);
    my $cov = cov($v1,$v2);

And then either query the values or print them like so:

    print "The covariance between $v1 and $v2: $covariance\n";
    my $cq = $cov->query;
    my $c0 = 0+$cov;

Create a 20 point "moving" covariance like so:

    my $sth = $dbh->prepare("select col1,col2 from data where something");
    my $len = 20;
    my $cov = cov();
       $cov->set_size($len);

    $sth->execute or die $dbh->errstr;
    $sth->bind_columns( my ($lhs, $rhs) ) or die $dbh->errstr;

    my $count = $len;
    while( $sth->fetch ) {

        $cov->insert( $lhs, $rhs );
        if( -- $count <= 0 ) {
            print "Covariance: $cov\n";
        }
    }

The full details are probably in the base module.  If you have questions, just
let me know.

=head1 AUTHOR

Paul Miller <jettero@cpan.org>

=head1 SEE ALSO

perl(1), L<Statistics::Basic>

=cut
